/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calcuation;

/**
 *
 * @author USER
 */
public class Calculators extends javax.swing.JFrame {

    double firstnum;
    double secondnum;
    double  result ;
    String operation;
    
    public Calculators() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jtxt = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jt4 = new javax.swing.JButton();
        jt1 = new javax.swing.JButton();
        jt2 = new javax.swing.JButton();
        jt3 = new javax.swing.JButton();
        jt6 = new javax.swing.JButton();
        jt5 = new javax.swing.JButton();
        jt7 = new javax.swing.JButton();
        jt8 = new javax.swing.JButton();
        jt0 = new javax.swing.JButton();
        jt9 = new javax.swing.JButton();
        jtp = new javax.swing.JButton();
        jtm = new javax.swing.JButton();
        jtd = new javax.swing.JButton();
        jtmul = new javax.swing.JButton();
        jtpm = new javax.swing.JButton();
        jtdecm = new javax.swing.JButton();
        jtequal = new javax.swing.JButton();
        jtcl = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 255));

        jtxt.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jt4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt4.setText("4");
        jt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt4ActionPerformed(evt);
            }
        });

        jt1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt1.setText("1");
        jt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt1ActionPerformed(evt);
            }
        });

        jt2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt2.setText("2");
        jt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt2ActionPerformed(evt);
            }
        });

        jt3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt3.setText("3");
        jt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt3ActionPerformed(evt);
            }
        });

        jt6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt6.setText("6");
        jt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt6ActionPerformed(evt);
            }
        });

        jt5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt5.setText("5");
        jt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt5ActionPerformed(evt);
            }
        });

        jt7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt7.setText("7");
        jt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt7ActionPerformed(evt);
            }
        });

        jt8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt8.setText("8");
        jt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt8ActionPerformed(evt);
            }
        });

        jt0.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt0.setText("0");
        jt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt0ActionPerformed(evt);
            }
        });

        jt9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jt9.setText("9");
        jt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jt9ActionPerformed(evt);
            }
        });

        jtp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtp.setText("+");
        jtp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpActionPerformed(evt);
            }
        });

        jtm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtm.setText("-");
        jtm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtmActionPerformed(evt);
            }
        });

        jtd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtd.setText("/");
        jtd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdActionPerformed(evt);
            }
        });

        jtmul.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtmul.setText("*");
        jtmul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtmulActionPerformed(evt);
            }
        });

        jtpm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtpm.setText("+-");
        jtpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtpmActionPerformed(evt);
            }
        });

        jtdecm.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtdecm.setText(".");
        jtdecm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtdecmActionPerformed(evt);
            }
        });

        jtequal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtequal.setText("=");
        jtequal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtequalActionPerformed(evt);
            }
        });

        jtcl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtcl.setText("Clear");
        jtcl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtclActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtd, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtcl, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(85, 85, 85)
                                    .addComponent(jtdecm, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jtequal, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtpm, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jtmul, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jt9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jt5, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                                .addComponent(jt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jt6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jt2, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                                                .addComponent(jt0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jtp, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                                        .addComponent(jt7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jt3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jtm, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jt8, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jt8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtp, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jt9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtdecm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtpm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtmul, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtd, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtcl, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtequal, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt1ActionPerformed
        // TODO add your handling code here:
        String Enternumber =jtxt.getText()+jt1.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_jt1ActionPerformed

    private void jt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt6ActionPerformed
        String Enternumber =jtxt.getText()+jt6.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_jt6ActionPerformed

    private void jt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt5ActionPerformed
       String Enternumber =jtxt.getText()+jt5.getText();
      jtxt.setText(Enternumber);
    }//GEN-LAST:event_jt5ActionPerformed

    private void jt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt7ActionPerformed
        String Enternumber =jtxt.getText()+jt7.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_jt7ActionPerformed

    private void jt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt8ActionPerformed
      //String Enternumber =jtxt.getText()+jt8.getText();
      String Enternumber =jt8.getText();
         jtxt.setText(Enternumber);  // TODO add your handling code here:
    }//GEN-LAST:event_jt8ActionPerformed

    private void jt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt0ActionPerformed
      String Enternumber =jtxt.getText()+jt0.getText();
        jtxt.setText(Enternumber);
    }//GEN-LAST:event_jt0ActionPerformed

    private void jt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt9ActionPerformed
        String Enternumber =jt9.getText();
           jtxt.setText(Enternumber);// TODO add your handling code here:
    }//GEN-LAST:event_jt9ActionPerformed

    private void jtpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpActionPerformed
       firstnum = Double.parseDouble(jtxt.getText());
        jtxt.setText("");
        operation="+";
    }//GEN-LAST:event_jtpActionPerformed

    private void jtmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtmActionPerformed
        firstnum = Double.parseDouble(jtxt.getText());
         jtxt.setText("");
         operation="-";// TODO add your handling code here:
    }//GEN-LAST:event_jtmActionPerformed

    private void jtdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdActionPerformed
    firstnum = Double.parseDouble(jtxt.getText());
    jtxt.setText("");
     operation="/";
    }//GEN-LAST:event_jtdActionPerformed

    private void jtmulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtmulActionPerformed
        firstnum = Double.parseDouble(jtxt.getText());
         jtxt.setText("");
         operation="*";// TODO add your handling code here:
    }//GEN-LAST:event_jtmulActionPerformed

    private void jtpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtpmActionPerformed
        double ops=Double.parseDouble(String.valueOf(jtxt.getText()));
          ops=ops*(-1);
           jtxt.setText(String.valueOf(ops));
    }//GEN-LAST:event_jtpmActionPerformed

    private void jtdecmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtdecmActionPerformed
     String Enternumber =jtxt.getText()+jtdecm.getText();
      jtxt.setText(Enternumber);    // TODO add your handling code here:
    }//GEN-LAST:event_jtdecmActionPerformed

    private void jtequalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtequalActionPerformed
       String answer;
      secondnum=Double.parseDouble(jtxt.getText());
  if( (operation =="+"))
    {
 
      result=firstnum+secondnum;
      answer=String.format("%.0f",result);
      
      jtxt.setText(answer);
        } 
  
  if(operation=="-")
 {
   result=firstnum-secondnum;
  answer=String.format("%.0f",result);
   jtxt.setText(answer);

}
   if(operation=="/")
 {
   result=firstnum/secondnum;
  answer=String.format("%.0f",result);

     jtxt.setText(answer);

}
   
    if(operation=="*")
 {
   result=firstnum*secondnum;
  answer=String.format("%.0f",result);

     jtxt.setText(answer);

}
    }//GEN-LAST:event_jtequalActionPerformed

    private void jtclActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtclActionPerformed
      jtxt.setText("");
    }//GEN-LAST:event_jtclActionPerformed

    private void jt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt3ActionPerformed
       String Enternumber =jtxt.getText()+jt3.getText();
             jtxt.setText(Enternumber);
    }//GEN-LAST:event_jt3ActionPerformed

    private void jt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt2ActionPerformed
       String Enternumber =jtxt.getText()+jt2.getText();
       jtxt.setText(Enternumber); // TODO add your handling code here:
    }//GEN-LAST:event_jt2ActionPerformed

    private void jt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jt4ActionPerformed
      String Enternumber =jtxt.getText()+jt4.getText();
      jtxt.setText(Enternumber);
    }//GEN-LAST:event_jt4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculators().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jt0;
    private javax.swing.JButton jt1;
    private javax.swing.JButton jt2;
    private javax.swing.JButton jt3;
    private javax.swing.JButton jt4;
    private javax.swing.JButton jt5;
    private javax.swing.JButton jt6;
    private javax.swing.JButton jt7;
    private javax.swing.JButton jt8;
    private javax.swing.JButton jt9;
    private javax.swing.JButton jtcl;
    private javax.swing.JButton jtd;
    private javax.swing.JButton jtdecm;
    private javax.swing.JButton jtequal;
    private javax.swing.JButton jtm;
    private javax.swing.JButton jtmul;
    private javax.swing.JButton jtp;
    private javax.swing.JButton jtpm;
    private javax.swing.JTextField jtxt;
    // End of variables declaration//GEN-END:variables
}
